# Generated by Django 3.1.8 on 2021-04-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=64, unique=True, verbose_name='Section Name')),
                ('secType', models.CharField(choices=[('page', 'Single Page'), ('category', 'Category')], default='page', max_length=64, verbose_name='Section Type')),
                ('template', models.CharField(blank=True, choices=[('blank', 'Blank'), ('content', 'Content'), ('default', 'Default'), ('desc', 'Descriptive'), ('simple', 'Simple'), ('simple_alt', 'Simple (Alt.)'), ('simple_desc', 'Simple (Descriptive)')], default='default', max_length=32)),
                ('display_photo', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='Display Photo')),
                ('order', models.IntegerField(default=0, verbose_name='Catalog Order')),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catalog Section',
                'verbose_name_plural': 'Catalog',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=190, unique=True)),
                ('item_sku', models.CharField(blank=True, max_length=190, null=True, unique=True)),
                ('category', models.CharField(choices=[('COFFEE', 'Coffee'), ('TEA', 'Tea')], default='COFFEE', max_length=32)),
                ('item_description', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, choices=[('AC', 'Active'), ('CL', 'Clearance'), ('CS', 'Coming Soon'), ('FT', 'Featured'), ('IN', 'Inactive'), ('NW', 'New')], default='AC', max_length=32)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Cost')),
                ('landed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Landed Cost')),
                ('price_wholesale', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('price_retail', models.IntegerField(blank=True, null=True, verbose_name='Retail Price')),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Photo')),
                ('product_photo_alt', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Alt. Product Photo')),
                ('catalog_photo', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Catalog Photo')),
                ('Hidden', models.BooleanField(default=False)),
                ('grind', models.CharField(blank=True, choices=[('DRIP', 'Drip'), ('ESPRESSO', 'Espresso'), ('PERC', 'Percolator/Press Pot'), ('WHOLEBEAN', 'Whole Bean')], default='DRIP', max_length=32)),
                ('product_set', models.BooleanField(blank=True, default=False, verbose_name='Product Set')),
                ('catalog', models.BooleanField(blank=True, default=True)),
                ('web', models.BooleanField(blank=True, default=True)),
                ('price_list', models.BooleanField(blank=True, default=False, verbose_name='Price List')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='')),
                ('set_photo', models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Product Photo')),
                ('set_catalog_photo', models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Catalog Photo')),
            ],
        ),
    ]
